// data.js
window.wordsPool = {
    text:[
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "i", "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
    "this", "but", "his", "by", "from", "they", "we", "say", "her", "she", "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
    "so", "up", "out", "if", "about", "who", "get", "which", "go", "me", "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
    "people", "into", "year", "your", "good", "some", "could", "them", "see", "other", "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
    "back", "after", "use", "two", "how", "our", "work", "first", "well", "way", "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
    "is", "am", "are", "was", "were", "been", "has", "had", "did", "should", "might", "must", "shall", "may", "here", "where", "why", "both", "each", "few",
    "more", "some", "such", "nor", "own", "same", "too", "very", "every", "least", "less", "many", "much", "always", "never", "sometimes", "often", "usually", "seldom", "rarely",
    "once", "twice", "before", "since", "until", "while", "during", "against", "among", "between", "through", "without", "under", "above", "below", "down", "front", "side", "left", "right",
    "inside", "outside", "near", "far", "next", "last", "another", "different", "similar", "together", "alone", "public", "private", "life", "world", "man", "woman", "child", "family", "group",
    "system", "company", "program", "government", "number", "point", "home", "water", "room", "mother", "area", "money", "story", "fact", "month", "lot", "right", "study", "book", "eye",
    "job", "word", "business", "issue", "side", "kind", "head", "house", "service", "friend", "father", "power", "hour", "game", "line", "end", "member", "law", "car", "city",
    "community", "name", "president", "team", "minute", "idea", "body", "information", "back", "parent", "face", "others", "level", "door", "office", "war", "history", "party", "result", "change",
    "morning", "reason", "research", "girl", "guy", "moment", "air", "teacher", "force", "education", "foot", "boy", "age", "policy", "music", "market", "sense", "nation", "plan", "college",
    "interest", "death", "experience", "effect", "use", "class", "control", "care", "field", "development", "role", "effort", "rate", "heart", "drug", "show", "leader", "light", "voice", "wife",
    "whole", "police", "mind", "finally", "pull", "return", "free", "military", "price", "report", "decision", "son", "view", "relationship", "town", "road", "arm", "difference", "value", "building",
    "action", "full", "model", "season", "society", "tax", "director", "position", "player", "record", "paper", "space", "ground", "form", "event", "official", "matter", "center", "couple", "site",
    "project", "activity", "star", "table", "need", "court", "american", "oil", "situation", "industry", "fig", "street", "image", "itself", "phone", "data", "practice", "piece", "land", "product",
    "doctor", "wall", "patient", "worker", "news", "test", "movie", "north", "love", "open", "step", "baby", "computer", "type", "attention", "film", "republic", "tree", "source", "organization",
    "hair", "look", "century", "evidence", "station", "plant", "growth", "degree", "support", "governor", "section", "civil", "future", "coach", "sea", "dream", "shuttle", "earth", "art", "style",
    "adult", "history", "god", "performance", "charge", "active", "rest", "worry", "top", "operation", "threat", "bar", "glass", "skill", "social", "authority", "blood", "fund", "nature", "professor",
    "apart", "size", "spring", "store", "oxford", "movement", "visual", "common", "gold", "board", "general", "term", "fall", "machine", "object", "base", "catch", "clear", "modern", "leave",
    "arrive", "send", "choose", "grow", "happen", "create", "allow", "invent", "discover", "understand", "read", "write", "speak", "watch", "remember", "forget", "learn", "teach", "meet", "follow",
    "stop", "start", "begin", "continue", "finish", "spend", "buy", "sell", "pay", "cost", "increase", "decrease", "drop", "rise", "raise", "reduce", "develop", "produce", "build", "destroy",
    "kill", "die", "live", "stay", "remain", "wait", "expect", "hope", "wish", "prefer", "accept", "refuse", "agree", "disagree", "complain", "suggest", "advise", "warn", "encourage", "prevent",
    "protect", "save", "waste", "share", "hide", "show", "appear", "disappear", "seem", "sound", "feel", "taste", "smell", "touch", "press", "pull", "push", "shake", "break", "fix",
    "repair", "clean", "wash", "dirty", "dry", "wet", "hot", "cold", "warm", "cool", "dark", "light", "bright", "heavy", "light", "hard", "soft", "smooth", "rough", "sharp",
    "blunt", "flat", "round", "square", "long", "short", "tall", "low", "high", "deep", "shallow", "wide", "narrow", "thick", "thin", "fat", "slim", "beautiful", "ugly", "pretty",
    "handsome", "smart", "clever", "stupid", "foolish", "wise", "ignorant", "rich", "poor", "wealthy", "expensive", "cheap", "valuable", "useless", "useful", "powerful", "weak", "strong", "brave", "cowardly",
    "polite", "rude", "kind", "cruel", "friendly", "hostile", "honest", "dishonest", "loyal", "jealous", "greedy", "generous", "selfish", "proud", "humble", "modest", "lazy", "diligent", "careful", "careless",
    "patient", "impatient", "calm", "nervous", "anxious", "excited", "bored", "tired", "exhausted", "sleepy", "awake", "dead", "alive", "healthy", "sick", "ill", "injured", "painful", "comfortable", "uncomfortable",
    "safe", "dangerous", "risky", "secure", "vulnerable", "hidden", "secret", "public", "private", "local", "national", "global", "international", "foreign", "native", "natural", "artificial", "synthetic", "organic", "chemical",
    "physical", "mental", "emotional", "spiritual", "religious", "secular", "legal", "illegal", "moral", "immoral", "ethical", "logical", "illogical", "rational", "irrational", "scientific", "historical", "political", "economic", "financial",
    "commercial", "industrial", "agricultural", "cultural", "artistic", "musical", "literary", "technical", "technological", "digital", "virtual", "cyber", "electronic", "mechanical", "electrical", "magnetic", "optical", "acoustic", "thermal", "nuclear",
    "solar", "lunar", "stellar", "cosmic", "universal", "eternal", "infinite", "finite", "temporary", "permanent", "constant", "variable", "stable", "unstable", "steady", "unsteady", "smooth", "jerky", "fluid", "solid",
    "gas", "liquid", "vapor", "plasma", "crystal", "powder", "dust", "smoke", "fog", "cloud", "rain", "snow", "ice", "frost", "storm", "wind", "breeze", "gale", "hurricane", "tornado",
    "earthquake", "volcano", "flood", "drought", "famine", "plague", "disease", "infection", "virus", "bacteria", "parasite", "fungus", "plant", "animal", "human", "person", "man", "woman", "child", "baby",
    "teenager", "adult", "elderly", "ancestor", "descendant", "family", "relative", "parent", "mother", "father", "sibling", "brother", "sister", "spouse", "husband", "wife", "child", "son", "daughter", "grandparent",
    "grandchild", "friend", "enemy", "ally", "rival", "competitor", "opponent", "partner", "colleague", "employee", "employer", "boss", "manager", "director", "executive", "president", "leader", "follower", "member", "citizen",
    "subject", "native", "foreigner", "immigrant", "emigrant", "refugee", "tourist", "visitor", "guest", "host", "customer", "client", "patient", "doctor", "nurse", "lawyer", "judge", "police", "soldier", "officer"
    ],
    code: {
        javascript: [
            "const data = await fetch('/api/v1/status');",
            "const unique = [...new Set(array)];",
            "const active = items.filter(x => x.isActive);",
            "setTimeout(() => { resolve(true); }, 1000);",
            "Object.keys(config).forEach(key => delete config[key]);",
            "const res = await Promise.all(queue.map(req => req()));",
            "export default function init({ target, mode }) {",
            "if (!response.ok) throw new Error('Network failure');",
            "const payload = JSON.stringify({ id: Date.now(), ...body });",
            "localStorage.setItem('user_session', JSON.stringify(token));",
            "document.addEventListener('DOMContentLoaded', (e) => {",
            "const element = document.querySelector('.terminal-panel');",
            "return items.reduce((acc, current) => acc + current.value, 0);",
            "try { const data = JSON.parse(raw); } catch (err) { return null; }",
            "class Controller extends Component { constructor(props) { super(props); } }"
        ],
        cpp: [
            "#include <iostream>",
            "std::vector<std::string> words;",
            "int main(int argc, char* argv[]) {",
            "for (int i = 0; i < limit; ++i) {",
            "std::cout << \"SYSTEM_LOAD_OK\" << std::endl;",
            "auto ptr = std::make_unique<Node>();",
            "template <typename T> class Matrix {",
            "if (status != 200) { return EXIT_FAILURE; }",
            "void update(float deltaTime) override {",
            "unsigned int bitmask = 1 << 4;",
            "std::sort(data.begin(), data.end());",
            "const auto& [key, value] = current_pair;",
            "throw std::runtime_error(\"Null pointer exception\");",
            "typedef std::map<int, std::string> IdentityMap;",
            "std::fstream file(\"config.json\", std::ios::in);"
        ],
        java: [
            "public static void main(String[] args) {",
            "List<String> list = new ArrayList<>();",
            "System.out.println(\"// REBOOT_SYSTEM_INITIALIZED\");",
            "Map<String, Object> map = new HashMap<>();",
            "public class MainController implements Runnable {",
            "@Override public void run() { synchronized(lock) {",
            "Optional<User> user = userRepository.findById(id);",
            "stream.filter(Objects::nonNull).forEach(System.out::println);",
            "throw new IllegalArgumentException(\"Invalid runtime arguments\");",
            "try (BufferedReader br = new BufferedReader(new FileReader(path))) {",
            "private final ExecutorService executor = Executors.newFixedThreadPool(4);",
            "String json = new ObjectMapper().writeValueAsString(payload);",
            "CompletableFuture.runAsync(() -> processQueue()).thenAccept(v -> done());",
            "public interface DataAccessObject<T> { T find(long id); }",
            "boolean isActive = status.stream().anyMatch(s -> s.isLive());"
        ]
    }
};

// Map to window.typingData to match the lookups in your main script engine file smoothly
window.typingData = window.wordsPool;